<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "entity"
 *
 * Auto generated by Extension Builder 2020-11-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'Entity',
	'description' => 'Basic TYPO3 extension for managing entities',
	'category' => 'plugin',
	'author' => 'Christian Pschorr',
	'author_email' => 'pschorr.christian@gmail.com',
	'state' => 'beta',
	'uploadfolder' => 0,
	'clearCacheOnLoad' => 0,
	'version' => '2.0.0',
	'constraints' => [
		'depends' => [
			'typo3' => '12.0.0-12.4.99',
			'ps14_foundation' => '2.0.0-2.99.99',
		],
		'conflicts' => [],
		'suggests' => [],
	],
];
